---
- import_tasks: install.yml
  become: true
  tags:
    - bind_exporter_install

- import_tasks: configure.yml
  become: true
  tags:
    - bind_exporter_install

- name: enable  bind_exporter to start on boot
  become: true
  systemd:
    daemon_reload: true
    name: bind_exporter
    enabled: true
    state: started
  tags:
    - bind_exporter_install
